[tool.poetry]
name = "balcony"
version = "0.0.8"
description = "AWS API for humans"
authors = ["Oguzhan Yilmaz <oguzhanylmz271@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"

[tool.poetry.scripts]
balcony = "balcony.cli:run_app"

[tool.poetry.dependencies]
python = "^3.7"
typer = "^0.6.1"
rich = "^12.5.1"
boto3 = "^1.24.80"
jmespath = "^1.0.1"
inflect = "^6.0.0"

[tool.poetry.group.dev.dependencies]
nose3 = "^1.3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
